#Conectando com o Drive

In [1]:
from google.colab import drive

In [2]:
drive.mount('/content/drive/')

Mounted at /content/drive/

In [3]:
import pandas as pd

In [49]:
dados = pd.read_csv('/content/drive/MyDrive/Curso Análise de Dados - Eu ProgrAmo/dados.csv')

#Conectando SQL com Pandas

In [5]:
import sqlite3

In [13]:
conexao = sqlite3.connect('/content/drive/MyDrive/Curso Análise de Dados - Eu ProgrAmo/Módulo 5/Status_Brasil')

In [7]:
query = "SELECT * FROM Municipios_Brasileiros WHERE cidade LIKE '%Mogi%';"

In [14]:
pd.read_sql(query, con=conexao) #variável de conexão

   municipio_ID           cidade estado   regiao
0          1715          Itamogi     MG  Sudeste
1          5122  Mogi Das Cruzes     SP  Sudeste
2          5123       Mogi Guaçu     SP  Sudeste
3          5124       Mogi Mirim     SP  Sudeste

In [29]:
query2 = '''SELECT Municipios_Brasileiros.estado, AVG(Municipio_Status.renda) FROM Municipios_Brasileiros
          INNER JOIN Municipio_Status ON Municipios_Brasileiros.municipio_ID = Municipio_Status.municipio_ID GROUP BY Municipios_Brasileiros.estado;'''

In [30]:
pd.read_sql(query2, con=conexao) #Média da renda por estado

   estado  AVG(Municipio_Status.renda)
0      AC                     0.585455
1      AL                     0.548363
2      AM                     0.545113
3      AP                     0.618875
4      BA                     0.574805
5      CE                     0.559293
6      DF                     0.863000
7      ES                     0.680628
8      GO                     0.683980
9      MA                     0.531664
10     MG                     0.652008
11     MS                     0.687846
12     MT                     0.682149
13     PA                     0.572357
14     PB                     0.564423
15     PE                     0.574378
16     PI                     0.546813
17     PR                     0.691915
18     RJ                     0.704796
19     RN                     0.580183
20     RO                     0.658173
21     RR                     0.577867
22     RS                     0.722115
23     SC                     0.728038
24     SE                     0.577147
25     SP                     0.716571
26     TO                     0.610543

###Exemplo Lista em Python

In [36]:
salada = ['alface', 'tomate', 'cenoura']

In [37]:
print('eu gosto de {}'.format(', '.join(salada)))

eu gosto de alface, tomate, cenoura

##Utilizando a planilha dados.csv

In [43]:
#quero ver a renda por estado, mas só dos estados disponíveis na planilha dados

In [50]:
lista_estados = list(dados['UF ONDE MORA'].unique()) #transforma estados em lista
lista_estados

['DF',
 'PA',
 'MG',
 'CE',
 'SP',
 'RS',
 'BA',
 'RJ',
 'MS',
 'PB',
 'MT',
 'PR',
 'ES',
 nan,
 'SC',
 'PE',
 'RN',
 'SE',
 'AL',
 'GO',
 'MA',
 'AM',
 'PI']

In [44]:
query3 = '''SELECT Municipios_Brasileiros.estado, AVG(Municipio_Status.renda) FROM Municipios_Brasileiros
          INNER JOIN Municipio_Status ON Municipios_Brasileiros.municipio_ID = Municipio_Status.municipio_ID
          WHERE Municipios_Brasileiros.estado IN ({})
          GROUP BY Municipios_Brasileiros.estado;'''.format(', '.join(['?' for _ in lista_estados]))

In [46]:
estados_renda = pd.read_sql(query3, con=conexao, params=lista_estados) #passa os parâmetros/estados dentro da lista pra chamada
estados_renda

   estado  AVG(Municipio_Status.renda)
0      AL                     0.548363
1      AM                     0.545113
2      BA                     0.574805
3      CE                     0.559293
4      DF                     0.863000
5      ES                     0.680628
6      GO                     0.683980
7      MA                     0.531664
8      MG                     0.652008
9      MS                     0.687846
10     MT                     0.682149
11     PA                     0.572357
12     PB                     0.564423
13     PE                     0.574378
14     PI                     0.546813
15     PR                     0.691915
16     RJ                     0.704796
17     RN                     0.580183
18     RS                     0.722115
19     SC                     0.728038
20     SE                     0.577147
21     SP                     0.716571

In [51]:
dados.rename(columns={'UF ONDE MORA': 'ESTADO'}, inplace=True)

In [52]:
dados.columns

Index(['Unnamed: 0', 'ID', 'IDADE', 'FAIXA IDADE', 'GENERO', 'COR/RACA/ETNIA',
       'PCD', 'EXPERIENCIA_PROFISSIONAL_PREJUDICADA', 'ASPECTOS_PREJUDICADOS',
       'VIVE_NO_BRASIL', 'ESTADO ONDE MORA', 'ESTADO', 'REGIAO ONDE MORA',
       'MUDOU DE ESTADO?', 'REGIAO DE ORIGEM', 'NIVEL DE ENSINO',
       'ÁREA DE FORMAÇÃO', 'QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?', 'SETOR',
       'NUMERO DE FUNCIONARIOS', 'GESTOR?', 'CARGO COMO GESTOR', 'CARGO ATUAL',
       'NIVEL', 'FAIXA SALARIAL',
       'QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE DADOS VOCÊ TEM?',
       'QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE TI/ENGENHARIA DE SOFTWARE VOCÊ TEVE ANTES DE COMEÇAR A TRABALHAR NA ÁREA DE DADOS?',
       'SALARIO', 'NOVO_NIVEL', 'GERACAO',
       'Quanto tempo de experiência na área de dados você tem?',
       'Quanto tempo de experiência na área de TI/Engenharia de Software você teve antes de começar a trabalhar na área de dados?',
       'Você está satisfeito na sua empresa atual?',
       'Qual o principal motivo da sua insatisfação com a empresa atual?',
       'Você participou de entrevistas de emprego nos últimos 6 meses?',
       'Você pretende mudar de emprego nos próximos 6 meses?',
       'Quais os principais critérios que você leva em consideração no momento de decidir onde trabalhar?',
       'Atualmente qual a sua forma de trabalho?',
       'Qual a forma de trabalho ideal para você?',
       'Caso sua empresa decida pelo modelo 100% presencial qual será sua atitude?',
       'Sua empresa passu por Layoff em 2022?', 'Atuacao',
       'Quais das linguagens listadas abaixo você utiliza no trabalho?',
       'EM_BUSCA', 'ABERTO_OPORTUNIDADES', 'ETNIA_BRANCA', 'ETNIA_PARDA',
       'ETNIA_PRETA', 'ETNIA_AMARELA', 'ETNIA_INDIGENA', 'ETNIA_OUTRA',
       'ETNIA_PREFIRO_NAO_INFORMAR'],
      dtype='object')

In [68]:
dados = dados.merge(estados_renda, left_on='ESTADO', right_on='estado', how='left')

In [70]:
correlacao_renda_salario = dados['SALARIO'].corr(dados['AVG(Municipio_Status.renda)'])
correlacao_renda_salario

np.float64(0.12083384881429463)